#!/usr/bin/env bash

text=$1
keyid='alias/networth-api'
region='us-east-1'

aws kms encrypt --key-id $keyid --region $region --output text --query CiphertextBlob --plaintext $text
# aws kms encrypt --key-id $keyid --region $region --output text --query CiphertextBlob --plaintext fileb://temp.txt
